apiVersion: v1
kind: Service
metadata:
  name: {{ include "batch-job.fullname" . }}
  labels:
    {{- include "batch-job.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: batch-service
      protocol: TCP
      name: batch-service
  selector:
    {{- include "batch-job.selectorLabels" . | nindent 4 }}
